# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A. Grant Schissler, Statistician
email: aschissler at unr dot edu 
description: >- # this means to ignore newlines until "baseurl:"
  I'm an Asst. Prof. of Statistics in the Department of Math & Stats at the University of Nevada, Reno. My research interests are driven by interdisciplinary problems, often in the biomedical domain. My interests include Bayesian modeling, large-scale (high dimensional) inference, nof1 designs, massively-parallel computing (GPU), multivariate, RNA-seq, and simulation. Accessibility Comment. Not all of this site and external links are fully accessible. I'm working on it, but in the meantime please contact me if you need a more accessible version. For further assistance, please email accessibility at unr dot edu.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://www.grantschissler.com
twitter_username: GSchissler
github_username:  grizant
linkedin_username: grantschissler
google_scholar_username: 1H-SHoMAAAAJ

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-architect
# theme: jekyll-theme-hacker
# theme: minimal-mistakes-jekyll
# remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
